import Head from 'next/head'

function HTMLHead (props) {
  return (
    <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
  )
}

export default HTMLHead;